# gits/icons.py
# Note usage:  import gits.icons as ICONS. Then ICONS.CLEAN.
CLEAN   = "🧹"
CLONE   = "📥"
CONVERT = "🔄"
DELETE  = "🗑️"
DOC     = "🧪"
DONE    = "✅"
ERROR   = "❌"
GROUP   = "📦"
INFO    = "ℹ️"
PULL    = "⬇️"
REFRESH = "🔄"
REPO    = "📥"
STASH   = "📦"
STATUS  = "🔍"
SUCCESS = "✅"
TIME    = "⏱️"
WARNING = "⚠️"
